name: autod2d_app
description: A Flutter app for AutoD2D with listings and WebView support.
publish_to: 'none' # This prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  flutter_html: ^3.0.0-alpha.6
  transparent_image: ^2.0.0
  webview_flutter: ^4.2.2
  url_launcher: ^6.2.5
  flutter_dotenv: ^5.1.0   # ✅ NEW LINE

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
